# Generated by Django 3.2.8 on 2021-10-26 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from workouts.data import create_default_user, create_days

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('state', models.CharField(choices=[('AC', 'Active'), ('IN', 'Inactive'), ('AR', 'Archived')], default='AC', max_length=2)),
                ('days', models.ManyToManyField(to='workouts.Day')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(create_default_user.run),
        migrations.RunPython(create_days.run)
    ]
