# Generated by Django 3.2.8 on 2021-10-25 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='user',
            new_name='user_id',
        ),
    ]
