# Generated by Django 3.2.8 on 2021-10-25 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_rename_user_workout_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='user_id',
            new_name='user',
        ),
    ]
