# Generated by Django 3.2.8 on 2021-11-11 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_exercice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercice',
            name='exercice_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workouts.exercice'),
        ),
    ]
