# Generated by Django 3.2.8 on 2021-11-13 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_remove_exercice_exercice_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercice',
            name='position',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
