# Generated by Django 3.2.8 on 2021-11-13 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0009_session_start_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='workout',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='workouts.workout'),
            preserve_default=False,
        ),
    ]
