# Generated by Django 3.2.8 on 2021-11-13 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0010_session_workout'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetCompleted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repetition_number', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('position', models.IntegerField()),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.exercice')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.session')),
            ],
        ),
    ]
